language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

matrix:
  exclude:
    - php: 5.3
      env: TYPO3_BRANCH=master
    - php: 5.4
      env: TYPO3_BRANCH=master

env:
  - TYPO3_BRANCH=master
  - TYPO3_BRANCH=TYPO3_6-2

notifications:
  email:
    recipients:
      - lolli@schwarzbu.ch
    on_success: change
    on_failure: change

before_script:
  - sudo apt-get install parallel
  - composer self-update
  - cd ..
  - git clone --single-branch --branch $TYPO3_BRANCH --depth 1 https://github.com/TYPO3/TYPO3.CMS.git typo3_core
  - mv typo3_core/* .
  - composer install
  - mkdir -p typo3conf/ext
  - mv enetcache typo3conf/ext/

script:
  - >
    echo;
    echo "Running unit tests";
    ./bin/phpunit --colors -c typo3conf/ext/enetcache/Build/UnitTests.xml
  - >
    echo;
    echo "Running php lint";
    find typo3conf/ext/enetcache/ -name \*.php | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;
